POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mauri Kunnas",
    "number": "00-11-222333"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "00-11-222333"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mauri Kunnas"
}